[workspace]
authors = ["Logical Guess"]
channels = ["https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "butterfly"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
package = "pixi run mojo package butterfly"
bench = "pixi run package && cp butterfly.mojopkg tests/ && pixi run mojo run benches/bench.mojo -I tests/ && rm benches/butterfly.mojopkg"
test_basic = "pixi run package && cp butterfly.mojopkg tests/ && pixi run mojo run tests/test_basic.mojo -I tests/ && rm tests/butterfly.mojopkg"
test_encode_value = "pixi run package && cp butterfly.mojopkg tests/ && pixi run mojo run tests/test_encode_value.mojo -I tests/ && rm tests/butterfly.mojopkg"
test_measure = "pixi run package && cp butterfly.mojopkg tests/ && pixi run mojo run tests/test_measure.mojo -I tests/ && rm tests/butterfly.mojopkg"

[dependencies]
mojo = "==0.25.6"
